import Footer from "./components/Footer";
import Marquee from "./components/Marquee";
import Products from "./components/Products";
import TopicCard from "./components/TopicCard";
import Video from "./components/Video";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Video />
        <Products />
        <TopicCard />
        <Marquee />
        <Footer />
      </body>
    </html>
  );
}
